# Generated by Django 2.2.6 on 2019-10-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20191001_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_add',
            new_name='date_added',
        ),
    ]
